# Generated by Django 2.1.4 on 2019-01-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='members_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
