# Generated by Django 2.1.4 on 2019-03-07 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190218_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Center'),
        ),
    ]
